# Importações

In [1]:
# DONWLOAD DATASET:
#!pip install kagglehub

'''
import kagglehub

# Download latest version
path = kagglehub.dataset_download("akshaypawar7/millions-of-movies")

print("Path to dataset files:", path)
'''

'\nimport kagglehub\n\n# Download latest version\npath = kagglehub.dataset_download("akshaypawar7/millions-of-movies")\n\nprint("Path to dataset files:", path)\n'

In [2]:
#pip install pandas matplotlib scikit-learn

In [3]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

In [4]:
df =  pd.read_csv("movies.csv")

# Filtros

## Filmes ja lançados (status = Released)
Filmes que ainda não foram lançados não possuem dados importantes para a análise

In [5]:
df_status = df.drop_duplicates(subset=['status'])
df_status

,id,title,genres,original_language,overview,popularity,production_companies,release_date,budget,revenue,runtime,status,tagline,vote_average,vote_count,credits,keywords,poster_path,backdrop_path,recommendations
0,615656,Meg 2: The Trench,Action-Science Fiction-Horror,en,An exploratory dive into the deepest depths of...,8763.998,Apelles Entertainment-Warner Bros. Pictures-di...,2023-08-02,129000000.0,352056482.0,116.0,Released,Back for seconds.,7.079,1365.0,Jason Statham-Wu Jing-Shuya Sophia Cai-Sergio ...,based on novel or book-sequel-kaiju,/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg,/qlxy8yo5bcgUw2KAmmojUKp4rHd.jpg,1006462-298618-569094-1061181-346698-1076487-6...
600,911916,Spider-Man: Beyond the Spider-Verse,Animation-Action-Adventure-Science Fiction,en,The further continuing story of Miles Morales ...,101.444,Columbia Pictures-Sony Pictures Animation-Marv...,2024-03-27,0.0,0.0,0.0,In Production,NaN,0.000,0.0,Shameik Moore-Hailee Steinfeld-Oscar Isaac-Jak...,superhero-based on comic,/5cAuJOfd5tuuFBz2yQmBCtVBaj0.jpg,NaN,NaN
656,616851,Untitled 'The Walking Dead' Film,Adventure-Drama-Horror-Science Fiction,en,Follows Rick Grimes from the departure of his ...,95.508,AMC Networks-Skybound Entertainment-eOne Films,NaN,0.0,0.0,0.0,Planned,NaN,0.000,0.0,Andrew Lincoln-Pollyanna McIntosh,apocalypse-zombie-zombie apocalypse,/djHNpqX9lmsWhMmSBfwwxEPmlpP.jpg,NaN,NaN
727,575265,Mission: Impossible - The Final Reckoning,Action-Adventure-Thriller,en,After escaping a calamitous train crash Ethan ...,89.040,Paramount Pictures-Skydance Media-TC Productions,2025-05-21,400000000.0,0.0,0.0,Post Production,Our lives are the sum of our choices.,0.000,0.0,Tom Cruise-Ving Rhames-Simon Pegg-Hayley Atwel...,espionage-spy-secret agent-stunt-sequel-based ...,/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg,/chMU8WktxmICjAY48l62DUcevtv.jpg,NaN
2032,615129,Pokémon: Thám Tử Pikachu 2,Action-Adventure-Fantasy,en,A planned sequel to the 2019 film Pokémon Dete...,41.663,Legendary Pictures-The Pokémon Company,NaN,0.0,0.0,0.0,Canceled,NaN,0.000,0.0,Justice Smith-Ryan Reynolds-Kathryn Newton-Bil...,detective-based on video game-live action and ...,/knr2XAbotEtc2X2diStLvv4ovPX.jpg,NaN,NaN
14511,774079,Happy Death Day to Us,Thriller-Comedy,en,NaN,10.901,Universal Pictures-Blumhouse Productions,NaN,0.0,0.0,0.0,Rumored,NaN,0.000,0.0,Jessica Rothe-Rachel Matthews-Israel Broussard...,NaN,/ue5wV2XLP6KRsFLX7ak14DyqT87.jpg,NaN,NaN

In [6]:
registros_antes = len(df)
df = df[df['status'] == 'Released']
registros_depois = len(df)
print(f"Registros perdidos com o filtro: {registros_antes - registros_depois}")

Registros perdidos com o filtro: 5223

## Registros duplicados
Não faz sentido ter o mesmo filme mais de uma vez

In [7]:
registros_antes = len(df)
df = df.drop_duplicates()
registros_depois = len(df)
print(f"Registros perdidos com o filtro: {registros_antes - registros_depois}")

Registros perdidos com o filtro: 0

### Duplicados por titulo e data de lançamento

In [8]:
duplicados = df[df.duplicated(subset=['title', 'release_date'], keep=False)]
exemplo = df[df['title'].isin(['The Eighth Clause', 'Battle: Freestyle'])].sort_values(by='title')
exemplo.head(10)

,id,title,genres,original_language,overview,popularity,production_companies,release_date,budget,revenue,runtime,status,tagline,vote_average,vote_count,credits,keywords,poster_path,backdrop_path,recommendations
126,785521,Battle: Freestyle,Romance-Drama,no,Amalie and Mikael lead their street dance team...,333.723,Friland Produksjon AS,2022-04-01,0.0,0.0,88.0,Released,NaN,5.1,28.0,Lisa Teige-Fabian Svegaard Tapia-Ellen Dorrit ...,paris france-based on novel or book-norway-dan...,/6D6QumiHEhnpZG12Ibjy2BxA6n4.jpg,/8WpRRiz3qQqzBiifCTm1dW0b6bs.jpg,818750-790525-800407-739993-946726-682344-9532...
198,785521,Battle: Freestyle,Romance-Drama,no,Amalie and Mikael lead their street dance team...,238.540,Friland Produksjon AS,2022-04-01,0.0,0.0,88.0,Released,NaN,5.1,30.0,Lisa Teige-Fabian Svegaard Tapia-Ellen Dorrit ...,paris france-based on novel or book-norway-dan...,/6D6QumiHEhnpZG12Ibjy2BxA6n4.jpg,/8WpRRiz3qQqzBiifCTm1dW0b6bs.jpg,818750-790525-800407-739993-946726-682344-9532...
234,785521,Battle: Freestyle,Romance-Drama,no,Amalie and Mikael lead their street dance team...,210.928,Friland Produksjon AS,2022-04-01,0.0,0.0,88.0,Released,NaN,5.1,30.0,Lisa Teige-Fabian Svegaard Tapia-Ellen Dorrit ...,paris france-based on novel or book-norway-dan...,/6D6QumiHEhnpZG12Ibjy2BxA6n4.jpg,/8WpRRiz3qQqzBiifCTm1dW0b6bs.jpg,818750-790525-800407-739993-946726-682344-9532...
13,956101,The Eighth Clause,Thriller,la,Kat and Borja appear to be a perfect couple bu...,2259.303,SDB Films-El Hombre Orquesta,2022-04-29,0.0,0.0,0.0,Released,NaN,4.6,10.0,Maite Perroni-Manuel Vega-Óscar Jaenada-Jessic...,NaN,/8tc8eMFAX2SDC1TRu987qFQy8Cl.jpg,/kLnqNE9Af5QHyvUxw8cDGhF1ilv.jpg,NaN
15815,841524,The Eighth Clause,Drama-Thriller,es,Kat and Borja appear to be a perfect couple bu...,10.293,SDB Films-El Hombre Orquesta-Expansión Films E...,2022-04-29,0.0,0.0,80.0,Released,NaN,4.2,6.0,Maite Perroni-Manuel Vega-Óscar Jaenada-Jessic...,NaN,/5CbVMeLvaGn87gx05waiIJ0JySr.jpg,/uA0nUh1JerC4TkNiTzwS4B5kjTN.jpg,769636-346651-324542-343674-227970

In [9]:
registros_antes = len(df)
df = df.drop_duplicates(subset=['title', 'release_date'])
registros_depois = len(df)
print(f"Registros perdidos com o filtro: {registros_antes - registros_depois}")

Registros perdidos com o filtro: 61422

In [10]:
exemplo = df[df['title'].isin(['The Eighth Clause', 'Battle: Freestyle'])].sort_values(by='title')
exemplo.head()

,id,title,genres,original_language,overview,popularity,production_companies,release_date,budget,revenue,runtime,status,tagline,vote_average,vote_count,credits,keywords,poster_path,backdrop_path,recommendations
126,785521,Battle: Freestyle,Romance-Drama,no,Amalie and Mikael lead their street dance team...,333.723,Friland Produksjon AS,2022-04-01,0.0,0.0,88.0,Released,NaN,5.1,28.0,Lisa Teige-Fabian Svegaard Tapia-Ellen Dorrit ...,paris france-based on novel or book-norway-dan...,/6D6QumiHEhnpZG12Ibjy2BxA6n4.jpg,/8WpRRiz3qQqzBiifCTm1dW0b6bs.jpg,818750-790525-800407-739993-946726-682344-9532...
13,956101,The Eighth Clause,Thriller,la,Kat and Borja appear to be a perfect couple bu...,2259.303,SDB Films-El Hombre Orquesta,2022-04-29,0.0,0.0,0.0,Released,NaN,4.6,10.0,Maite Perroni-Manuel Vega-Óscar Jaenada-Jessic...,NaN,/8tc8eMFAX2SDC1TRu987qFQy8Cl.jpg,/kLnqNE9Af5QHyvUxw8cDGhF1ilv.jpg,NaN

## Budget > 0
Filmes com budget igual a 0 ou negativo, representam inconssitência com as informações, trazendo erros para a analise

In [11]:
registros_antes = len(df)
df = df[df['budget'] > 0]
registros_depois = len(df)
print(f"Registros perdidos com o filtro: {registros_antes - registros_depois}")

Registros perdidos com o filtro: 622512

## Runtime > 70
Filmes com runtime menores que 70 não são considerados longa-metragem, que é nosso foco

In [12]:
registros_antes = len(df)
df = df[df['runtime'] > 70]
registros_depois = len(df)
print(f"Registros perdidos com o filtro: {registros_antes - registros_depois}")

Registros perdidos com o filtro: 12383

## Vote_count > 30
Filmes com poucos votos, podem levantar erros estatisticos sobre a analise dos filmes, pois o target 'vote_average' poderá ficar enviesado

In [13]:
registros_antes = len(df)
df = df[df['vote_count'] > 30]
registros_depois = len(df)
print(f"Registros perdidos com o filtro: {registros_antes - registros_depois}")

Registros perdidos com o filtro: 9956

## Removendo colunas que não serão utilizadas na análise
- Title -> não usaremos processamento textual
- Overview -> não usaremos processamento textual
- Production Companies -> Vale com o One Hot Encoding? 
- Revenue -> Vazamento de dados.
- Status -> registro unico agr, ent inutil
- Tagline -> não usaremos processamento textual e 85% dos registros são NaN
- vote_avarege -> TARGET 
- vote_count -> vazamento de dados.
- Credits -> Vale com o One Hot Encoding?
- Keywords -> não usaremos processamento textual e 71% dos registros são NaN
- Poster_path e Backdrop_path -> não faz sentido para a análise
- Recommendations -> não faz sentido para a análise, 95% dos valores são NaN, vazamento de dados

In [14]:
df = df.drop(columns=[
    'id','title', 'overview', 'revenue', 'status', 'tagline', 
    'vote_count', 'poster_path', 'backdrop_path', 'recommendations', 'keywords',
    'credits'
])

# Colunas que serão utilizadas na análise
print("Colunas que serão utilizadas na análise:")
print(df.columns)

Colunas que serão utilizadas na análise:
Index(['genres', 'original_language', 'popularity', 'production_companies',
       'release_date', 'budget', 'runtime', 'vote_average'],
      dtype='object')

## Limpando todos os valores nulos

In [15]:
registros_antes = len(df)
df = df.dropna()
registros_depois = len(df)
print(f"Registros perdidos com o filtro: {registros_antes - registros_depois}")

Registros perdidos com o filtro: 231

# To CSV
informações do dataset filtrado

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10590 entries, 0 to 598651
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   genres                10590 non-null  object
 1   original_language     10590 non-null  object
 2   popularity            10590 non-null  float64
 3   production_companies  10590 non-null  object
 4   release_date          10590 non-null  object
 5   budget                10590 non-null  float64
 6   runtime               10590 non-null  float64
 7   vote_average          10590 non-null  float64
dtypes: float64(4), object(4)
memory usage: 744.6+ KB

In [17]:
df.describe()

         popularity        budget       runtime  vote_average
count  10590.000000  1.059000e+04  10590.000000  10590.000000
mean      30.970914  2.392062e+07    108.099245      6.364052
std      181.275201  3.720596e+07     22.109043      0.905434
min        0.600000  1.000000e+00     71.000000      1.800000
25%        8.322250  3.000000e+06     93.000000      5.800000
50%       12.904500  1.000000e+07    103.000000      6.400000
75%       22.545000  2.800000e+07    118.000000      7.000000
max     8763.998000  4.600000e+08    608.000000      9.000000

In [ ]:
#df.to_csv('filmes_filtrados.csv', index=False)